apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lumina-plane.fullname" . }}
  labels:
    {{- include "lumina-plane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lumina-plane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lumina-plane.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: {{ .Values.env.mongoUri | quote }}
            - name: GROQ_API_KEY
              value: {{ .Values.env.groqApiKey | quote }}
            - name: INFISICAL_CLIENT_ID
              value: {{ .Values.env.infisicalClientId | quote }}
            - name: INFISICAL_CLIENT_SECRET
              value: {{ .Values.env.infisicalClientSecret | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
